site_name: Google Maps

theme:
  name: material
  language: pt
  logo: ./assets/logos/google-logo.png
  font:
    text: Roboto
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate

markdown_extensions:
  - attr_list
  - md_in_html