site_name: Google Maps

theme:
  name: material
  language: pt
  logo: ./assets/logos/google-logo.png
  font:
    text: Roboto
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow
    
markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - search
  - include_dir_to_nav

docs_dir: './docs'

nav:
  - Início: index.md
  - Planejamento: planejamento
  - Encontros: encontros
  - Pré-Rastreabilidade: pre_rastreabilidade
  - Elicitação: elicitação
  - Apresentações: entregas.md