site_name: Carteira Digital de Trânsito

theme:
  name: material
  language: pt
  logo: ./assets/carteira-digital-transito-logo.png
  font:
    text: Roboto
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
 
