site_name: Google Maps

theme:
  name: material
  language: pt
  logo: ./assets/google-logo.png
  font:
    text: Roboto
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
 
